name: youtube_data_v3
description: A youtubeV3 package which contains functions to access Youtube Data API V3 via the API key.
version: 0.0.1+1
author: Aditya <cvadityagithub@gmail.com>
homepage: https://github.com/cvaditya1/youtube_data_v3

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:

  http: ^0.12.0+2
  googleapis: ^0.53.0
  googleapis_auth: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
